const houses=window.JEMMO_HOUSES, creators=window.JEMMO_CREATORS;
let currentId=localStorage.getItem('jemmo_house')||'unicornio';
let joined=localStorage.getItem('jemmo_joined_'+currentId)==='yes';
let chat=JSON.parse(localStorage.getItem('jemmo_house_chat_'+currentId)||'null')||[
 {name:'Jesús',text:'Bienvenidos a nuestra Casa. Respeto y buen ambiente.'},
 {name:'Marta',text:'Buenas tardes familia.'},{name:'Carlos',text:'Hoy estamos todos unidos.'}
];
const $=id=>document.getElementById(id);let tt;
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(tt);tt=setTimeout(()=>$('toast').classList.remove('show'),2200)}
function house(){return houses.find(h=>h.id===currentId)||houses[0]}
function applyTheme(h){document.documentElement.style.setProperty('--house',h.color);document.documentElement.style.setProperty('--accent',h.accent)}
function renderHouse(){const h=house();applyTheme(h);$('topName').textContent=h.name;$('topMotto').textContent=h.motto;$('houseName').textContent=h.name;$('motto').textContent=h.motto+' · '+h.theme;$('agent').textContent='Agente: '+h.agent;$('crest').textContent=h.crest;$('rank').textContent=h.rank;$('members').textContent=h.members;$('online').textContent=h.online;$('live').textContent=h.live;$('notice').textContent='📢 '+h.notice;renderSeats();renderChat();}
function renderSeats(){const local=creators.filter(c=>c.house===currentId).slice(0,5);const fillers=[...local];while(fillers.length<7)fillers.push({name:['Nerea','Noa','Dani','Ruth','Yandira','Leo'][fillers.length%6],level:20+fillers.length});let html=fillers.slice(0,7).map((c,i)=>`<button class="seat" data-creator="${c.id||''}"><i class="light"></i><span class="avatar">${c.name[0]}</span><span><b>${c.name}</b><small>Nivel ${c.level||22} · ${i===0?'moderadora':'miembro'}</small></span></button>`).join('');html+=joined?`<button class="seat" id="mySeat"><i class="light"></i><span class="avatar">J</span><span><b>Jesús</b><small>Tú · en la silla</small></span></button>`:`<button class="seat free" id="freeSeat"><span class="avatar">+</span><span><b>Silla libre</b><small>Toca para subirte</small></span></button>`;$('seatGrid').innerHTML=html;document.querySelectorAll('[data-creator]').forEach(b=>b.onclick=()=>{const c=creators.find(x=>x.id===b.dataset.creator);if(c)openProfile(c)});const f=$('freeSeat');if(f)f.onclick=joinSeat;const m=$('mySeat');if(m)m.onclick=leaveSeat;$('joinBtn').textContent=joined?'Bajarme de la silla':'Subirme a la silla'}
function joinSeat(){joined=true;localStorage.setItem('jemmo_joined_'+currentId,'yes');renderSeats();toast('Has subido a la silla de '+house().name)}
function leaveSeat(){joined=false;localStorage.removeItem('jemmo_joined_'+currentId);renderSeats();toast('Has bajado de la silla')}
function renderChat(){$('messages').innerHTML=chat.map(m=>`<div class="msg"><span class="avatar">${m.name[0]}</span><div><b>${m.name}</b><p>${m.text}</p></div></div>`).join('');$('messages').scrollTop=$('messages').scrollHeight}
function send(){const v=$('chatInput').value.trim();if(!v)return;chat.push({name:'Jesús',text:v});localStorage.setItem('jemmo_house_chat_'+currentId,JSON.stringify(chat));$('chatInput').value='';renderChat()}
function switchHouse(id){currentId=id;joined=localStorage.getItem('jemmo_joined_'+currentId)==='yes';chat=JSON.parse(localStorage.getItem('jemmo_house_chat_'+currentId)||'null')||[{name:'Sistema',text:'Has entrado en '+houses.find(h=>h.id===id).name+'.'},{name:'Anfitrión',text:'Bienvenido a nuestra comunidad.'}];localStorage.setItem('jemmo_house',id);$('elevatorSheet').classList.remove('show');renderHouse();scrollTo({top:0,behavior:'smooth'});toast('Puertas abiertas · '+house().name)}
function renderHouseList(q=''){const s=q.toLowerCase();$('houseList').innerHTML=houses.filter(h=>h.name.toLowerCase().includes(s)).map((h,i)=>`<div class="house-row"><div class="mini-crest" style="background:linear-gradient(145deg,${h.accent},${h.color})">${h.crest}</div><div><b>${i+1}. ${h.name}</b><small style="display:block;color:#aaa3b4">${h.members} miembros · ${h.online} conectados</small></div><button class="visit" data-house="${h.id}">Visitar</button></div>`).join('');document.querySelectorAll('[data-house]').forEach(b=>b.onclick=()=>switchHouse(b.dataset.house))}
function renderCreators(){const h=house();applyTheme(h);$('creatorGrid').innerHTML=creators.map(c=>{const ch=houses.find(x=>x.id===c.house);return `<button class="creator-card" data-profile="${c.id}" style="--house:${ch.color};--accent:${ch.accent};color:white;text-align:left"><span class="live-badge">LIVE</span><span class="viewer">◉ ${c.viewers>=1000?(c.viewers/1000).toFixed(1)+'K':c.viewers}</span><div class="big-avatar">${c.name[0]}</div><b>${c.name}</b><small>${ch.name}</small><small>🟡 ${c.coins.toLocaleString('es-ES')}</small></button>`}).join('');document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>openProfile(creators.find(c=>c.id===b.dataset.profile)))}
function openProfile(c){const h=houses.find(x=>x.id===c.house);$('profileContent').innerHTML=`<button class="secondary" id="closeProfile">← Volver</button><div class="profile-head" style="--house:${h.color};--accent:${h.accent}"><div class="big-avatar">${c.name[0]}</div><h2>${c.name}</h2><p>${h.name} · Nivel ${c.level}</p><p style="color:#aaa3b4">${c.bio}</p></div><div class="house-meta"><div class="stat"><b>${c.followers.toLocaleString('es-ES')}</b><small>SEGUIDORES</small></div><div class="stat"><b>${c.viewers}</b><small>EN DIRECTO</small></div><div class="stat"><b>${c.coins.toLocaleString('es-ES')}</b><small>COINS</small></div></div><div class="profile-actions"><button class="primary" id="followCreator">Seguir</button><button class="secondary" id="enterRoom">Entrar a su Audio Room</button></div>`;$('profileSheet').classList.add('show');$('closeProfile').onclick=()=>$('profileSheet').classList.remove('show');$('followCreator').onclick=()=>toast('Ahora sigues a '+c.name);$('enterRoom').onclick=()=>toast('Entrando al Audio Room simulado de '+c.name)}
$('menuBtn').onclick=()=>$('drawer').classList.add('show');$('closeDrawer').onclick=()=>$('drawer').classList.remove('show');$('drawer').onclick=e=>{if(e.target===$('drawer'))$('drawer').classList.remove('show')};$('walletBtn').onclick=()=>toast('Monedero de prueba · 125.680 coins');$('elevatorBtn').onclick=()=>{$('elevatorSheet').classList.add('show');renderHouseList()};$('closeElevator').onclick=()=>$('elevatorSheet').classList.remove('show');$('houseSearch').oninput=e=>renderHouseList(e.target.value);$('onlineBtn').onclick=$('navOnline').onclick=()=>{$('onlineSheet').classList.add('show');renderCreators()};$('closeOnline').onclick=()=>$('onlineSheet').classList.remove('show');$('profileSheet').onclick=e=>{if(e.target===$('profileSheet'))$('profileSheet').classList.remove('show')};$('sendBtn').onclick=send;$('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter')send()});$('clearChat').onclick=()=>{chat=[];localStorage.removeItem('jemmo_house_chat_'+currentId);renderChat();toast('Chat local limpiado')};$('joinBtn').onclick=()=>joined?leaveSeat():joinSeat();$('audioBtn').onclick=()=>toast('Audio Room de la Casa · simulación local');renderHouse();
